###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: spotted-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=roliveira
        - MYSQL_DATABASE=spotted
        - MYSQL_USER=ricardo
        - MYSQL_PASSWORD=roliveira
      ports:
        - "1027:3306"

    webserver:
      image: nginx:alpine
      container_name: spotted-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "1025:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: spotted-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

